name: Build

on:
  pull_request: # All
  push:
    branches:
    - main
  release:
    types: [created]  # Runs when a new release is created in the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hardware-variant:
          - leaf_3_2_2
          - leaf_3_2_3
          - leaf_3_2_5
        behavior-variant:
          - dev
          - release
        exclude:
          - hardware-variant: leaf_3_2_2
            behavior-variant: release
    name: ${{ matrix.hardware-variant }} ${{ matrix.behavior-variant }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run --environment ${{ matrix.hardware-variant }}_${{ matrix.behavior-variant }}

      - name: Upload firmware artifacts
        if: matrix.behavior-variant == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.hardware-variant }}
          path: |
            .pio/build/${{ matrix.hardware-variant }}_${{ matrix.behavior-variant }}/firmware*.bin
