name: PlatformIO

on:
  pull_request: # All
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pio-env:
          - leaf_3_2_2_dev
          - leaf_3_2_3_dev
          - leaf_3_2_3_release
          - leaf_3_2_5_dev
          - leaf_3_2_5_release
    name: Build ${{ matrix.pio-env }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run --environment ${{ matrix.pio-env }}

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            .pio/build/*/firmware.bin
