name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed  # Runs after the build workflow completes (everything needs to be built before we can update the release)

jobs:
  release:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'release' && 
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Copy newest hardware firmware to firmware.bin
        # Backwards compatibility: Release 0.0.9 and earlier expect a file named "firmware.bin"
        run: |
          highest_version="0.0.0"
          highest_file=""

          # Iterate over firmware files
          for file in artifacts/firmware-leaf_*.bin; do
            # Extract XX, YY, and ZZ using regex
            if [[ $file =~ firmware-leaf_([0-9]+)_([0-9]+)_([0-9]+)\.bin ]]; then
              xx=${BASH_REMATCH[1]}
              yy=${BASH_REMATCH[2]}
              zz=${BASH_REMATCH[3]}
              version="$xx.$yy.$zz"

              # Compare versions
              if [[ $(printf '%s\n' "$highest_version" "$version" | sort -V | tail -n1) == "$version" ]]; then
                highest_version="$version"
                highest_file="$file"
              fi
            fi
          done

          # Copy the highest version firmware to artifacts/firmware.bin
          if [[ -n "$highest_file" ]]; then
            cp "$highest_file" artifacts/firmware.bin
            echo "Selected firmware: $highest_file (version $highest_version)"
          else
            echo "No firmware files found!" >&2
            exit 1
          fi

      - name: List downloaded files (debugging)
        run: ls -R artifacts

      - name: Upload artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.workflow_run.head_branch }}
          files: artifacts/**/*
